In [2]:
import pandas as pd
import numpy as np

In [5]:
s =pd.Series([23, 24, 25, 26])



# Indexing
print(s[0])    
print(s[2])   

print(s.index)    

# Custom Indexing
s2 = pd.Series([23, 24, 25, 26], index = ["Adam", "Eve", "Charlie", "Bob"])
print(s2["Eve"])   
print(s2["Bob"])    

# Vectorized Operations
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

print(s1 + s2)

# Mutable Values but immutable size
s = pd.Series([1, 2, 3, 4, 5])
s[0] = 100

print(s)

changed_s = s.drop(1)
print(changed_s)
s = pd.Series([23, 24, 25, 26])
print(s)

print(s)

23
25
RangeIndex(start=0, stop=4, step=1)
24
26
0    5
1    7
2    9
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
2      3
3      4
4      5
dtype: int64
0    23
1    24
2    25
3    26
dtype: int64
0    23
1    24
2    25
3    26
dtype: int64

In [6]:
# DataFrame in pandas - using dictionary
info = {
    "Name" : ["Adam", "Eve", "Bob"],
    "Marks" : [78, 99, 85],
    "Grade" : ['B', 'O', 'A']
}

df = pd.DataFrame(info)

print(df)
print(type(df))

print(df.index)       
print(df.columns)      

# DataFrom using Numpy array
np_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(np_arr, columns=["Col1", "Col2", "Col3"])
print(df)

# DataFrom using Lists
l = [["Adam", 96], ["Eve", 75], ["Bob", 82], ["Charlie", 92]]
df = pd.DataFrame(l, columns=["Name", "Marks"])
print(df)

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks', 'Grade'], dtype='object')
   Col1  Col2  Col3
0     1     2     3
1     4     5     6
2     7     8     9
      Name  Marks
0     Adam     96
1      Eve     75
2      Bob     82
3  Charlie     92

In [8]:
# pandas with csv files
data = pd.read_csv("employee_data.csv")
print(data)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [9]:
# DataFrame Methods
df = pd.read_csv("employee_data.csv")

print(df.head())
print(df.tail())
print(df.sample())
print(df.info())
print(df.shape)
print(df.describe())
print(df.columns)
print(df.nunique())

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000
   ID   Name  Age Department  Salary
3   4  David   45  Marketing   91000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes
None
(10, 5)
             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000
Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')
ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [11]:
# Cleaning Data
df = pd.read_csv("raw_data.csv") 

# Handle Missing values
df.isnull()           
df.isnull().sum()      

df.dropna()           
df.dropna(axis = 1)    

df.fillna(0)           # fills NaN with value
df["age"] = df["age"].fillna(df["age"].mean())          

df.ffill()             # forward fill
df.bfill()             # backward fill

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  51000.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6    Ahmed Khan  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     USA     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [12]:
# Handle Duplicate values
df = pd.read_csv("raw_data.csv") 

df.duplicated()                      
df.duplicated("country")             
df.duplicated(["country", "gender"]) 

df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [13]:
# Handle Data Types
df = pd.read_csv("raw_data.csv") 

df.dtypes                                
df2 = df.fillna(0).copy()
df2["income"] = df2["income"].astype(int)     

# String type
df2["gender"].str.lower()                     
df2["gender"].str.upper()                   
df2["gender"].str.capitalize()                

df2["gender"].str.capitalize()               
df2["name"].str.split(" ")                    
type(df2["name"].str.split(" ")[0])            

df2["country"].str.contains("US")
df2["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [14]:
# Transformation / Feature Engineering
df2 = df.copy()

# apply a fnx to a row or col
df2["tax"] = df2["income"].apply(lambda x : "10%" if x < 60000 else "20%")

# map values to another
new_gender_vals = {"Male": "M", "Female": "F", "Unknown": "U"}
df2["gender"] = df2["gender"].map(new_gender_vals)

# assign some new values
df2.assign(new_income = df2["income"] * 1.1)

# replace specific values
df2["country"].replace("USA", "United States of America")

0     United States of America
1     United States of America
2                       Canada
3     United States of America
4                        Spain
5                        China
6                        India
7                          NaN
8     United States of America
9                       Mexico
10    United States of America
Name: country, dtype: object

In [15]:
# Transformation - Sorting
df2 = df.copy()

# Renaming
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income"]
df2.rename(columns={"Income": "Salary"})
df2.rename(index={0: "first"})

# Sorting - values & index
df2.sort_values("Income")                 
df2.sort_values("Income", ascending=False)    
df2.sort_values(["Age", "Income"])           

sorted_df2 = df2.sort_values(["Age", "Income"])
sorted_df2.sort_index()

# Reset Index
sorted_df2.reset_index()
sorted_df2.reset_index(drop=True)    

# Ranking
df2["Ranking"] = df2["Income"].rank(ascending=False, method="dense")

# Reorder
df2[["Id", "Name", "Age", "Income", "Gender", "Country", "Ranking"]]

    Id          Name   Age   Income   Gender Country  Ranking
0    1      John Doe  29.0  55000.0     Male     USA      5.0
1    1      John Doe  29.0  55000.0     Male     USA      5.0
2    2    Jane Smith   NaN  62000.0   Female  Canada      3.0
3    3          Alex   NaN  47000.0  Unknown     USA      7.0
4    4  Maria Garcia  34.0      NaN   Female   Spain      NaN
5    5        Li Wei  27.0  51000.0     Male   China      6.0
6    6           NaN  45.0  73000.0   Female   India      1.0
7    7    Ahmed Khan  38.0  68000.0     Male     NaN      2.0
8    8    Rachel Lee  29.0  62000.0   Female     USA      3.0
9    9   Carlos Ruiz   NaN  45000.0     Male  Mexico      8.0
10  10   Emily Davis  31.0  58000.0      NaN     USA      4.0

In [16]:
# Task - shift id column to end
df2 = df.copy()

new_col_order = [col for col in df.columns if col != "id"] + ["id"]
df2[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [17]:
# Writing to csv files
df = pd.read_csv("raw_data.csv") 

df.drop_duplicates(inplace=True)
df.sort_values("income", inplace=True)

df.to_csv("sorted_data.csv")   # to preserve index
df.to_csv("sorted_data.csv", index=False)   # to renew index

json_string = df.to_json()
print(json_string)

{"id":{"9":9,"3":3,"5":5,"0":1,"10":10,"2":2,"8":8,"7":7,"6":6,"4":4},"name":{"9":"Carlos Ruiz","3":"Alex","5":"Li Wei","0":"John Doe","10":"Emily Davis","2":"Jane Smith","8":"Rachel Lee","7":"Ahmed Khan","6":null,"4":"Maria Garcia"},"age":{"9":null,"3":null,"5":27.0,"0":29.0,"10":31.0,"2":null,"8":29.0,"7":38.0,"6":45.0,"4":34.0},"country":{"9":"Mexico","3":"USA","5":"China","0":"USA","10":"USA","2":"Canada","8":"USA","7":null,"6":"India","4":"Spain"},"gender":{"9":"Male","3":"Unknown","5":"Male","0":"Male","10":null,"2":"Female","8":"Female","7":"Male","6":"Female","4":"Female"},"income":{"9":45000.0,"3":47000.0,"5":51000.0,"0":55000.0,"10":58000.0,"2":62000.0,"8":62000.0,"7":68000.0,"6":73000.0,"4":null}}

In [18]:
# Grouping & Aggregation
df2 = df.copy()

df2.groupby("country")["income"].mean()    
df2.groupby("gender")["income"].mean()      

df2.groupby("country")["gender"].count()       
df2.groupby("gender")["income"].max()      

df2.groupby("country")["income"].agg(["mean", "min", "max"])       
df2.groupby("country")["income"].aggregate(["mean", "min", "max"])   

df2.groupby("country")["income"].agg(avg_salary="mean", max_salary="max")  

df2.groupby("country").agg({
    "age": "mean",
    "income": "mean"
})   # aggregate on multiple cols

df2.groupby("country").agg(
    avg_age=("age", "mean"),
    avg_salary=("income", "mean")
)   # rename aggregates on multiple cols

           avg_age  avg_salary
country
Canada         NaN     62000.0
China    27.000000     51000.0
India    45.000000     73000.0
Mexico         NaN     45000.0
Spain    34.000000         NaN
USA      29.666667     55500.0

In [21]:
# Melt & Pivot
df = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 18, 22]
})

melted = df.melt(
    id_vars=["country", "year"],     
    value_vars=["sales", "profit"],  
    var_name="metric",               
    value_name="value (in Lakhs)"   
)

print(melted)

original = melted.pivot(
    index=["country", "year"],   
    columns="metric",            
    values="value (in Lakhs)"    
)

print(original)

  country  year  metric  value (in Lakhs)
0     USA  2020   sales               100
1     USA  2021   sales               120
2   India  2020   sales                90
3   India  2021   sales               110
4     USA  2020  profit                20
5     USA  2021  profit                25
6   India  2020  profit                18
7   India  2021  profit                22
metric        profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [22]:
# Merging & Joining
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

pd.merge(df_customers, df_orders, on="customer_id")                  # Inner Join
pd.merge(df_customers, df_orders, on="customer_id", how="left")      # Left Join
pd.merge(df_customers, df_orders, on="customer_id", how="right")     # Right Join
pd.merge(df_customers, df_orders, on="customer_id", how="outer")      # Outer Join

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0